default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: amenux_development
  username: amenux  # Use minúsculas
  password: Ahauntmex3

test:
  <<: *default
  database: amenux_test
  username: amenux  # Use minúsculas
  password: Ahauntmex3

production:
  <<: *default
  database: amenux_production
  username: amenux  # Use minúsculas
  password: <%= ENV["AMENUX_PROJECT_DATABASE_PASSWORD"] %>
